apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
      ports:
        - name: web
          containerPort: 8888
          protocol: TCP
