apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hello
  labels:
    app: hello
    {{- include "hello-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello
      {{- include "hello-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: hello
        {{- include "hello-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          command: ["python", "/www/server.py"]
          livenessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app
              mountPath: /www
      volumes:
        - name: app
          configMap:
            name: {{ .Release.Name }}-hello-server
